name: swift-ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Switch Xcode version
        run: sudo xcode-select -s /Applications/Xcode_13.4.app
      - name: Build
        run: xcodebuild -scheme WorldTime -project ./WorldTime.xcodeproj -sdk macosx build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" | xcpretty && exit ${PIPESTATUS[0]}
